development:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_development
  pool: 5
<<<<<<< HEAD
  username: peterlai
=======
  username: grangerabuhoff
>>>>>>> cef3e80bf135356cc88f6bf0f4dbe7e2835d4d83
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_test
  pool: 5
<<<<<<< HEAD
  username: peterlai
=======
  username: grangerabuhoff
>>>>>>> cef3e80bf135356cc88f6bf0f4dbe7e2835d4d83
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_production
  pool: 5
<<<<<<< HEAD
  username: peterlai
  password:
=======
  username: grangerabuhoff
  password:
>>>>>>> cef3e80bf135356cc88f6bf0f4dbe7e2835d4d83
